### ISSUE TITLE
Timer Entity Support

### ISSUE THREAD

**Issue by Jab2870** [ytilis/hass-progress-bar-feature#1]
Hi, thanks for creating this. I am struggling to get it working with a HA [timer entity](https://www.home-assistant.io/integrations/timer/)

You can see the entity below with the available attributes

![Image](https://github.com/user-attachments/assets/180d0958-810f-4a4c-a8d4-a3f5ceba3395)

The yaml I'm using for the feature

```yaml
type: custom:progress-bar-feature
position: bottom
entity: timer.upstairs_heating
color: meter
time:
  end: finishes_at
  duration: duration
```

Unfortunately, the bar on the card never seems to update. This screenshot was taken around the 30second mark of the 1 minute timer so should have been about half full.

![Image](https://github.com/user-attachments/assets/060b16ef-1f23-4bd3-888a-440d1bfe789f)

Let me know if I can get anything else that would be helpful in recreating this
